export interface Indicator {
  id: string;
  name: string;
  type: 'pH' | 'redox' | 'complexometric' | 'adsorption' | 'fluorescent' | 'universal';
  pHRange?: [number, number];
  pKa?: number;
  colorAcidic: string;
  colorBasic: string;
  colorTransition?: string;
  concentration: string;
  solvent: string;
  molecularWeight?: number;
  formula?: string;
  casNumber?: string;
  applications: string[];
  notes?: string;
}

export const INDICATORS: Indicator[] = [
  // pH Indicators
  {
    id: 'methyl-violet',
    name: 'Methyl Violet',
    type: 'pH',
    pHRange: [0.0, 1.6],
    colorAcidic: 'Yellow',
    colorBasic: 'Violet',
    concentration: '0.05% in water',
    solvent: 'Water',
    molecularWeight: 393.95,
    formula: 'C₂₄H₂₈ClN₃',
    casNumber: '548-62-9',
    applications: ['Strong acid titrations', 'Very low pH detection'],
  },
  {
    id: 'thymol-blue-acid',
    name: 'Thymol Blue (1st transition)',
    type: 'pH',
    pHRange: [1.2, 2.8],
    pKa: 1.65,
    colorAcidic: 'Red',
    colorBasic: 'Yellow',
    concentration: '0.1% in 20% ethanol',
    solvent: 'Ethanol/Water',
    molecularWeight: 466.59,
    formula: 'C₂₇H₃₀O₅S',
    casNumber: '76-61-9',
    applications: ['Acid range pH measurement', 'Diprotic acid titrations'],
  },
  {
    id: 'methyl-orange',
    name: 'Methyl Orange',
    type: 'pH',
    pHRange: [3.1, 4.4],
    pKa: 3.46,
    colorAcidic: 'Red',
    colorBasic: 'Yellow',
    colorTransition: 'Orange',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 327.33,
    formula: 'C₁₄H₁₄N₃NaO₃S',
    casNumber: '547-58-0',
    applications: ['Strong acid-strong base', 'Alkalinity determination', 'Water hardness'],
  },
  {
    id: 'bromocresol-green',
    name: 'Bromocresol Green',
    type: 'pH',
    pHRange: [3.8, 5.4],
    pKa: 4.66,
    colorAcidic: 'Yellow',
    colorBasic: 'Blue',
    concentration: '0.1% in 20% ethanol',
    solvent: 'Ethanol/Water',
    molecularWeight: 698.01,
    formula: 'C₂₁H₁₄Br₄O₅S',
    casNumber: '76-60-8',
    applications: ['Protein electrophoresis', 'Weak acid titrations', 'Albumin assay'],
  },
  {
    id: 'methyl-red',
    name: 'Methyl Red',
    type: 'pH',
    pHRange: [4.4, 6.2],
    pKa: 5.00,
    colorAcidic: 'Red',
    colorBasic: 'Yellow',
    concentration: '0.1% in ethanol',
    solvent: 'Ethanol',
    molecularWeight: 269.30,
    formula: 'C₁₅H₁₅N₃O₂',
    casNumber: '493-52-7',
    applications: ['Mixed indicator titrations', 'Ammonium salt analysis', 'Kjeldahl nitrogen'],
  },
  {
    id: 'bromothymol-blue',
    name: 'Bromothymol Blue',
    type: 'pH',
    pHRange: [6.0, 7.6],
    pKa: 7.10,
    colorAcidic: 'Yellow',
    colorBasic: 'Blue',
    colorTransition: 'Green',
    concentration: '0.1% in 20% ethanol',
    solvent: 'Ethanol/Water',
    molecularWeight: 624.38,
    formula: 'C₂₇H₂₈Br₂O₅S',
    casNumber: '76-59-5',
    applications: ['Neutral pH detection', 'CO₂ measurement', 'Aquarium testing', 'Cell culture'],
  },
  {
    id: 'phenol-red',
    name: 'Phenol Red',
    type: 'pH',
    pHRange: [6.8, 8.4],
    pKa: 7.90,
    colorAcidic: 'Yellow',
    colorBasic: 'Red',
    colorTransition: 'Orange',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 354.38,
    formula: 'C₁₉H₁₄O₅S',
    casNumber: '143-74-8',
    applications: ['Swimming pool testing', 'Cell culture media', 'Biological pH monitoring'],
  },
  {
    id: 'thymol-blue-base',
    name: 'Thymol Blue (2nd transition)',
    type: 'pH',
    pHRange: [8.0, 9.6],
    pKa: 8.90,
    colorAcidic: 'Yellow',
    colorBasic: 'Blue',
    concentration: '0.1% in 20% ethanol',
    solvent: 'Ethanol/Water',
    molecularWeight: 466.59,
    formula: 'C₂₇H₃₀O₅S',
    casNumber: '76-61-9',
    applications: ['Base range pH measurement', 'Carbonate analysis'],
  },
  {
    id: 'phenolphthalein',
    name: 'Phenolphthalein',
    type: 'pH',
    pHRange: [8.2, 10.0],
    pKa: 9.40,
    colorAcidic: 'Colorless',
    colorBasic: 'Pink/Magenta',
    concentration: '0.1% in 90% ethanol',
    solvent: 'Ethanol',
    molecularWeight: 318.32,
    formula: 'C₂₀H₁₄O₄',
    casNumber: '77-09-8',
    applications: ['Acid-base titrations', 'Alkalinity', 'Concrete carbonation', 'FFA determination'],
    notes: 'Most common acid-base indicator. Becomes colorless above pH 13.',
  },
  {
    id: 'thymolphthalein',
    name: 'Thymolphthalein',
    type: 'pH',
    pHRange: [9.3, 10.5],
    pKa: 10.0,
    colorAcidic: 'Colorless',
    colorBasic: 'Blue',
    concentration: '0.1% in ethanol',
    solvent: 'Ethanol',
    molecularWeight: 430.54,
    formula: 'C₂₈H₃₀O₄',
    casNumber: '125-20-2',
    applications: ['High pH detection', 'Base titrations'],
  },
  {
    id: 'alizarin-yellow',
    name: 'Alizarin Yellow R',
    type: 'pH',
    pHRange: [10.1, 12.0],
    colorAcidic: 'Yellow',
    colorBasic: 'Red',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 287.23,
    formula: 'C₁₃H₈N₃NaO₅',
    casNumber: '2243-76-7',
    applications: ['Strong base determination', 'High pH titrations'],
  },
  {
    id: 'indigo-carmine',
    name: 'Indigo Carmine',
    type: 'pH',
    pHRange: [11.4, 13.0],
    colorAcidic: 'Blue',
    colorBasic: 'Yellow',
    concentration: '0.25% in water',
    solvent: 'Water',
    molecularWeight: 466.36,
    formula: 'C₁₆H₈N₂Na₂O₈S₂',
    casNumber: '860-22-0',
    applications: ['Very high pH detection', 'Food coloring analysis'],
  },

  // Redox Indicators
  {
    id: 'starch',
    name: 'Starch (Iodometric)',
    type: 'redox',
    colorAcidic: 'Colorless',
    colorBasic: 'Blue-Black',
    concentration: '1% freshly prepared in water',
    solvent: 'Water',
    applications: ['Iodometric titrations', 'Iodine detection', 'Vitamin C analysis', 'Chlorine determination'],
    notes: 'Add near endpoint. Forms blue-black complex with I₂. Use freshly prepared solution.',
  },
  {
    id: 'diphenylamine',
    name: 'Diphenylamine',
    type: 'redox',
    colorAcidic: 'Colorless',
    colorBasic: 'Violet',
    concentration: '1% in H₂SO₄',
    solvent: 'Sulfuric Acid',
    molecularWeight: 169.22,
    formula: 'C₁₂H₁₁N',
    casNumber: '122-39-4',
    applications: ['Dichromate titrations', 'Iron determination', 'COD analysis'],
    notes: 'E° = +0.76V. Oxidized form is violet.',
  },
  {
    id: 'ferroin',
    name: 'Ferroin (1,10-Phenanthroline Iron(II))',
    type: 'redox',
    colorAcidic: 'Red',
    colorBasic: 'Pale Blue',
    concentration: '0.025 M in water',
    solvent: 'Water',
    molecularWeight: 596.28,
    formula: '[Fe(phen)₃]²⁺',
    casNumber: '14634-91-4',
    applications: ['COD determination', 'Iron titrations', 'Cerium(IV) titrations', 'Redox potential measurement'],
    notes: 'E° = +1.06V. One of the most widely used redox indicators.',
  },
  {
    id: 'potassium-permanganate',
    name: 'Potassium Permanganate (Self-indicator)',
    type: 'redox',
    colorAcidic: 'Purple/Pink',
    colorBasic: 'Colorless (reduced)',
    concentration: '0.02 N standardized',
    solvent: 'Water',
    molecularWeight: 158.03,
    formula: 'KMnO₄',
    casNumber: '7722-64-7',
    applications: ['Permanganometry', 'Iron determination', 'Oxalate determination', 'H₂O₂ analysis'],
    notes: 'Self-indicating — excess KMnO₄ gives persistent pink color at endpoint.',
  },

  // Complexometric Indicators (for EDTA titrations)
  {
    id: 'ebt',
    name: 'Eriochrome Black T (EBT)',
    type: 'complexometric',
    colorAcidic: 'Wine Red (with metal)',
    colorBasic: 'Blue (free)',
    concentration: '0.5% in ethanol or triturated with NaCl',
    solvent: 'Ethanol',
    molecularWeight: 461.38,
    formula: 'C₂₀H₁₂N₃NaO₇S',
    casNumber: '1787-61-7',
    pHRange: [7, 11],
    applications: ['Total hardness (Ca²⁺ + Mg²⁺)', 'EDTA titrations', 'Water analysis'],
    notes: 'Works at pH 10 with NH₃/NH₄Cl buffer. Wine red → blue at endpoint.',
  },
  {
    id: 'murexide',
    name: 'Murexide (Ammonium Purpurate)',
    type: 'complexometric',
    colorAcidic: 'Pink (with Ca²⁺)',
    colorBasic: 'Purple (free)',
    concentration: 'Solid mixture with NaCl (1:100)',
    solvent: 'Solid/Water',
    molecularWeight: 302.20,
    formula: 'C₈H₈N₆O₆',
    casNumber: '3051-09-0',
    pHRange: [11, 13],
    applications: ['Calcium determination', 'EDTA titrations at high pH', 'Nickel & cobalt titrations'],
    notes: 'For Ca²⁺ only (not Mg²⁺). Use at pH 12+ with NaOH.',
  },
  {
    id: 'calcon',
    name: 'Calcon (Eriochrome Blue Black R)',
    type: 'complexometric',
    colorAcidic: 'Pink/Red (with Ca²⁺)',
    colorBasic: 'Blue (free)',
    concentration: '0.4% in ethanol',
    solvent: 'Ethanol',
    molecularWeight: 416.41,
    formula: 'C₂₀H₁₃N₂NaO₅S',
    casNumber: '2538-85-4',
    pHRange: [12, 14],
    applications: ['Calcium in cement', 'Calcium hardness', 'High pH Ca²⁺ titrations'],
    notes: 'Sharper endpoint than murexide for calcium.',
  },
  {
    id: 'xylenol-orange',
    name: 'Xylenol Orange',
    type: 'complexometric',
    colorAcidic: 'Red/Purple (with metal)',
    colorBasic: 'Yellow (free)',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 760.58,
    formula: 'C₃₁H₂₈N₂Na₄O₁₃S',
    casNumber: '3618-43-7',
    pHRange: [1, 6],
    applications: ['Lead determination', 'Zinc determination', 'Bismuth titrations', 'Heavy metal analysis'],
    notes: 'Works in acidic pH. Red → yellow at endpoint.',
  },
  {
    id: 'pAN',
    name: 'PAN (1-(2-Pyridylazo)-2-naphthol)',
    type: 'complexometric',
    colorAcidic: 'Red (with metal)',
    colorBasic: 'Yellow-Orange (free)',
    concentration: '0.1% in ethanol',
    solvent: 'Ethanol',
    molecularWeight: 249.27,
    formula: 'C₁₅H₁₁N₃O',
    casNumber: '85-85-8',
    pHRange: [2, 12],
    applications: ['Zinc', 'Copper', 'Cobalt', 'Nickel EDTA titrations', 'Multi-metal analysis'],
    notes: 'Very versatile. Can be used with many metal ions across wide pH.',
  },

  // Adsorption Indicators (for precipitation titrations)
  {
    id: 'fluorescein',
    name: 'Fluorescein (Mohr indicator alternative)',
    type: 'adsorption',
    colorAcidic: 'Yellow-Green fluorescence',
    colorBasic: 'Pink (adsorbed)',
    concentration: '0.1% in 70% ethanol',
    solvent: 'Ethanol/Water',
    molecularWeight: 332.31,
    formula: 'C₂₀H₁₂O₅',
    casNumber: '2321-07-5',
    applications: ['Chloride by Fajans method', 'AgNO₃ titrations', 'Halide determinations'],
    notes: 'Adsorbs on AgCl precipitate at endpoint. Keep solution dilute and acidic pH ~7.',
  },
  {
    id: 'eosin-y',
    name: 'Eosin Y',
    type: 'adsorption',
    colorAcidic: 'Orange',
    colorBasic: 'Magenta (adsorbed)',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 691.85,
    formula: 'C₂₀H₆Br₄Na₂O₅',
    casNumber: '17372-87-1',
    applications: ['Bromide & iodide by Fajans', 'Silver titrations'],
    notes: 'More strongly adsorbed than fluorescein. For Br⁻ and I⁻.',
  },
  {
    id: 'potassium-chromate',
    name: 'Potassium Chromate (Mohr method)',
    type: 'adsorption',
    colorAcidic: 'Yellow (solution)',
    colorBasic: 'Red-Brown (Ag₂CrO₄ precipitate)',
    concentration: '5% K₂CrO₄ in water',
    solvent: 'Water',
    molecularWeight: 194.19,
    formula: 'K₂CrO₄',
    casNumber: '7789-00-6',
    applications: ['Chloride by Mohr method', 'Silver nitrate titrations'],
    notes: 'pH 6.5–10.5. Forms brick-red Ag₂CrO₄ at endpoint after all Cl⁻ consumed.',
  },

  // Fluorescent Indicators
  {
    id: 'quinine-sulfate',
    name: 'Quinine Sulfate',
    type: 'fluorescent',
    pHRange: [3.0, 5.0],
    colorAcidic: 'Blue fluorescence',
    colorBasic: 'Non-fluorescent',
    concentration: '0.1% in 0.1N H₂SO₄',
    solvent: 'Sulfuric Acid',
    molecularWeight: 782.94,
    formula: '(C₂₀H₂₄N₂O₂)₂·H₂SO₄',
    casNumber: '6119-70-6',
    applications: ['Fluorometric pH measurement', 'UV calibration standard'],
  },
  {
    id: 'acridine',
    name: 'Acridine',
    type: 'fluorescent',
    pHRange: [5.2, 6.6],
    colorAcidic: 'Green fluorescence',
    colorBasic: 'Non-fluorescent',
    concentration: '0.05% in ethanol',
    solvent: 'Ethanol',
    molecularWeight: 179.22,
    formula: 'C₁₃H₉N',
    casNumber: '260-94-6',
    applications: ['Fluorometric titrations', 'Nucleic acid staining'],
  },

  // Universal / Mixed Indicators
  {
    id: 'universal-indicator',
    name: 'Universal Indicator',
    type: 'universal',
    pHRange: [1, 14],
    colorAcidic: 'Red (pH 1–3)',
    colorBasic: 'Violet (pH 11–14)',
    colorTransition: 'Orange→Yellow→Green→Blue across pH 3–11',
    concentration: 'Commercial mixture',
    solvent: 'Ethanol/Water',
    applications: ['Quick pH estimation', 'Education', 'Qualitative analysis', 'Water quality screening'],
    notes: 'Mixture of methyl red, bromothymol blue, thymol blue, and phenolphthalein. Not for precise titrations.',
  },
  {
    id: 'litmus',
    name: 'Litmus',
    type: 'pH',
    pHRange: [4.5, 8.3],
    colorAcidic: 'Red',
    colorBasic: 'Blue',
    concentration: 'Paper strips or 0.5% solution',
    solvent: 'Water',
    applications: ['Quick acid/base test', 'Qualitative analysis', 'Education'],
    notes: 'Natural indicator from lichens. Not precise — use pH indicators for quantitative work.',
  },
  {
    id: 'congo-red',
    name: 'Congo Red',
    type: 'pH',
    pHRange: [3.0, 5.0],
    colorAcidic: 'Blue-Violet',
    colorBasic: 'Red',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 696.66,
    formula: 'C₃₂H₂₂N₆Na₂O₆S₂',
    casNumber: '573-58-0',
    applications: ['Amyloid staining', 'pH indication', 'Free HCl in gastric fluid'],
  },
  {
    id: 'crystal-violet',
    name: 'Crystal Violet',
    type: 'pH',
    pHRange: [0.0, 1.8],
    colorAcidic: 'Yellow',
    colorBasic: 'Violet',
    concentration: '0.1% in water',
    solvent: 'Water',
    molecularWeight: 407.98,
    formula: 'C₂₅H₃₀ClN₃',
    casNumber: '548-62-9',
    applications: ['Non-aqueous titrations', 'Gram staining', 'Very strong acid detection'],
  },
];

export const INDICATOR_TYPES = [
  { value: 'pH', label: 'pH Indicators', description: 'Change color at specific pH values' },
  { value: 'redox', label: 'Redox Indicators', description: 'Change color at specific redox potentials' },
  { value: 'complexometric', label: 'Complexometric (EDTA)', description: 'For metal ion titrations with EDTA' },
  { value: 'adsorption', label: 'Adsorption / Precipitation', description: 'For precipitation titrations (Fajans, Mohr)' },
  { value: 'fluorescent', label: 'Fluorescent Indicators', description: 'Emit/quench fluorescence at specific pH' },
  { value: 'universal', label: 'Universal / Mixed', description: 'Cover wide pH range with multiple colors' },
] as const;
