export interface SOPEntry {
  id: string;
  name: string;
  category: string;
  principle?: string;
  apparatus?: string[];
  reagents?: string[];
  reagentPreparation?: { name: string; steps: string[] }[];
  procedure: string[];
  calculations?: string;
  resultInterpretation?: string;
}

export const SOP_DATA: SOPEntry[] = [
  {
    id: 'moisture',
    name: 'Moisture Determination',
    category: 'Proximate Analysis',
    principle: 'The moisture of feedstuffs is determined by heating the pre-weighed sample at 105°C under atmospheric pressure. Water content is removed as vapors.',
    apparatus: ['Electric weighing balance', 'Desiccator', 'Electric oven', 'Petri dish'],
    procedure: [
      'Take a labeled Petri dish and weigh it on a weighing balance and note the reading (W1).',
      'Tare the weighing balance and add 5-10g sample in the Petri dish.',
      'Place the Petri dish in a hot air oven at 135°C for 2 hours.',
      'Withdraw the sample from the oven after 2 hours and place it in desiccators for 15 minutes to cool.',
      'Again, weigh the sample (W2).',
    ],
    calculations: 'DM% = (W2 − W1) / Sample Weight × 100\nMoisture% = 100 − DM%',
  },
  {
    id: 'ash',
    name: 'Ash Determination',
    category: 'Proximate Analysis',
    principle: 'Total mineral elements are determined by igniting the sample and weighing the residue (ash). Used in conventional feed analysis for nitrogen-free extract (NFE) determination.',
    apparatus: ['Crucible', 'Desiccator', 'Electric weighing balance', 'Muffle furnace'],
    procedure: [
      'Take 2g feed sample in a cleaned, dried, already weighed crucible (W1).',
      'Ignite the sample in a muffle furnace at 550-650°C till white grey ash is obtained.',
      'Cool the residue in a desiccator and record the weight (W2).',
    ],
    calculations: 'Ash% = (W2 − W1) / Sample Weight × 100',
    resultInterpretation: 'Ash content represents the inorganic part of the ingredients. Higher ash than normal values requires acid-insoluble ash (AIA) determination.',
  },
  {
    id: 'ether-extract',
    name: 'Ether Extracts / Crude Fat',
    category: 'Proximate Analysis',
    principle: 'Ether or petroleum ether is volatilized and condensed; the condensed solvent drops on the sample to extract fat. Repeated volatilization and condensation extract fat from the feed sample.',
    apparatus: ['Soxhlet apparatus', 'Desiccator', 'Hot air oven', 'Digital weighing balance', 'Porous thimble or filter paper', 'Hot iron plate'],
    reagents: ['Feed sample', 'Fat-soluble solvent (ether, alcohol, acetone, hexane, chloroform, carbon tetrachloride)'],
    procedure: [
      'Take 3-5 grams of the feed sample in the thimble.',
      'Keep the sample in Soxhlet tube and fill ¾ with Hexane (125-150 ml).',
      'Place a weighed flask (W1) under the tube.',
      'Keep it on burner at 80°C for 3 hours.',
      'After 3 hours, remove it.',
      'Take a washing to recover hexane through the Soxhlet tube.',
      'Collect the oil and hexane mixture in a weighed flask.',
      'Put the flask in the oven for 8-10 minutes to evaporate hexane.',
      'Cool it and weigh it (W2).',
    ],
    calculations: 'Fat% = (W2 − W1) / Sample Weight × 100',
    resultInterpretation: 'Fish meal, feather meal, and rice polish are mainly tested for oil content.',
  },
  {
    id: 'crude-fiber',
    name: 'Crude Fiber Determination',
    category: 'Proximate Analysis',
    principle: 'After removal of moisture and fatty material, the sample is boiled with weak acid and then weak alkali to remove protein, sugar, and starches. Crude fiber is then determined along with some mineral material.',
    apparatus: ['Beakers', 'Thick linen cloth', 'Heating apparatus', 'China dish', 'Weighing balance', 'Muffle furnace', 'Hot air oven', 'Filtration flask (1L)', 'Funnel (120mm)'],
    reagents: ['10% H₂SO₄', '10% NaOH'],
    reagentPreparation: [
      { name: '10% H₂SO₄ Solution', steps: ['Take 102ml H₂SO₄ (98%)', 'Make 1000 ml volume with distilled water'] },
      { name: '10% NaOH Solution', steps: ['Take 100g pellet of NaOH (Merck)', 'Make 1000 ml volume with distilled water'] },
    ],
    procedure: [
      'Take 2g of the fat-free feed sample.',
      'Digest the fat-free sample in 10% H₂SO₄ (25ml) and add 250ml distilled water at simmering temperature for 35 minutes after boiling starts.',
      'Filter the contents through thick linen cloth and wash the residue with distilled water.',
      'Transfer the residue to another beaker containing 25ml 10% NaOH and add 250ml distilled water, then digest for 35 minutes at simmering temperature after boiling starts.',
      'Filter the contents and wash the residue with distilled water.',
      'Transfer residue in an already weighed china dish, dry in hot air oven for 2-3 hours at 135°C.',
      'Record the dry weight (W1), then ignite in muffle furnace at 600°C till grey/white ash (2 hours). Record weight (W2).',
    ],
    calculations: 'CF% = (W1 − W2) / Sample Weight × 100',
  },
  {
    id: 'crude-protein',
    name: 'Crude Protein Determination (Kjeldahl)',
    category: 'Proximate Analysis',
    principle: 'Conversion of nitrogenous compounds into ammonium sulphate by boiling with H₂SO₄, decomposition with 40% NaOH, collection of ammonia in acid solution, and titration against acid of known strength.',
    apparatus: ['Kjeldahl flask 500ml/300ml', 'Volumetric flask (250 or 100ml)', 'Micro Kjeldahl distillation apparatus', 'Pipette (2ml & 10ml)', 'Beakers (100ml)', 'Glass funnel'],
    reagents: ['N/10 H₂SO₄ (Ampoule)', '2% Boric acid (H₃BO₃)', '40% NaOH', '0.1% Methyl red indicator', 'Distilled water', 'Digestion mixture (K₂SO₄, FeSO₄, CuSO₄)', 'H₂SO₄ Lab Grade (97-98%)'],
    reagentPreparation: [
      { name: 'Digestion Mixture', steps: ['K₂SO₄ 90 parts (raise boiling point)', 'CuSO₄ 7 parts (catalyst)', 'FeSO₄ 3 parts (avoid bumping)'] },
      { name: '2% Boric Acid Solution', steps: ['Take 20g boric acid (Sigma)', 'Make 1000 ml with distilled water', 'Add 3-5ml methyl red indicator until light pink'] },
      { name: '40% NaOH Solution', steps: ['Take 400g NaOH pellet (Merck)', 'Make 1000 ml with distilled water'] },
    ],
    procedure: [
      'DIGESTION: Take 0.5g ground feed, add 5g digestion mixture in Kjeldahl flask, add 10ml lab grade H₂SO₄, heat till light green/colorless (60-80 min at 500-600°C).',
      'DILUTION: Transfer digestion contents to 100ml volumetric flask, add distilled water to make 100ml volume.',
      'DISTILLATION: Take 10ml sample in micro Kjeldahl apparatus, add 10ml 40% NaOH. Take another flask with 10ml 2% boric acid. Provide steam until ammonia is trapped (yellow endpoint). Wait 2 minutes.',
      'TITRATION: Titrate with 0.1N H₂SO₄ till light pink color. Record volume of acid used.',
    ],
    calculations: 'Factor = (0.1 × 14.0067 × 100 × 6.25 × 100) / (0.5 × 1000 × 10) = 17.5\nCP% = Factor × Titration value',
    resultInterpretation: 'Protein sources are tested via Kjeldahl method. Determines %N in sample to calculate CP. Mostly performed on plant and animal protein sources.',
  },
  {
    id: 'koh-solubility',
    name: 'KOH Solubility / PDI%',
    category: 'Protein Quality',
    principle: 'Plant proteins are soluble in weak alkali. Heat treatment reduces solubility. 1g sample in 50ml 0.2% KOH, stirred 20 min. Values of 75-80% solubility are ideal.',
    apparatus: ['Kjeldahl flask', 'Volumetric flask', 'Micro Kjeldahl distillation apparatus', 'Pipette', 'Beakers', 'Glass funnel', 'Magnetic stirrer', 'Centrifuge machine'],
    reagentPreparation: [
      { name: '0.2% KOH Solution (Method 1)', steps: ['Take 1N KOH ampoule, dissolve in 1000ml DW (mother solution)', 'Take 35.7ml from mother solution, make 1000ml with DW'] },
      { name: '0.2% KOH Solution (Method 2)', steps: ['Take 2.3g KOH pellet (85% Sigma)', 'Make 1000ml with DW'] },
    ],
    procedure: [
      'Take 1g sample in 100ml beaker, add 50ml 0.2% KOH, stir on magnetic stirrer 15-20 min.',
      'Take 2 plastic centrifuge tubes with equal sample. Centrifuge at 3000 rpm for 15 min.',
      'Take 2.5ml supernatant from both tubes (total 5ml).',
      'Add 5g digestion mixture and 10ml lab-grade H₂SO₄ to digestion flask.',
      'Heat at 500-600°C for 60-80 min till light green.',
      'Follow same procedure as CP estimation.',
    ],
    calculations: 'Sample Weight = (1g × 5ml) / 50ml = 0.1g\nFactor = (0.1 × 14.0067 × 100 × 6.25 × 100) / (0.1 × 1000 × 10) = 87.5\nKOH% = (Titration Reading × Factor × 100) / CP',
  },
  {
    id: 'true-protein',
    name: 'True Protein Estimation',
    category: 'Protein Quality',
    principle: 'When sample is treated with TCA solution, true protein is precipitated. Remaining nitrogen is dissolved and filtered out. Precipitate is determined for protein content.',
    apparatus: ['Kjeldahl flask', 'Volumetric flask', 'Micro Kjeldahl apparatus', 'Pipette', 'Beakers', 'Glass funnel', 'Filter paper', 'Vacuum pump', 'Magnetic stirrer', 'Hot air oven'],
    reagentPreparation: [
      { name: '5% TCA Solution', steps: ['Take 50g TCA (VWR)', 'Make 1000ml with distilled water'] },
    ],
    procedure: [
      'Take 1g sample in 100ml beaker, add 25ml 5% TCA solution.',
      'Stir on magnetic stirrer for 20 minutes.',
      'Cover and place in hot air oven at 60°C for 15 minutes.',
      'Filter with vacuum pump with filter paper and give a wash.',
      'Wrap and put filter paper in digestion flask.',
      'Add 5g digestion mixture and 15ml lab-grade H₂SO₄.',
      'Heat at 500-600°C for 60-80 min until light green.',
      'Follow same procedure as CP estimation.',
    ],
    calculations: 'Factor = (0.1 × 14.0067 × 100 × 6.25 × 100) / (1 × 1000 × 10) = 8.75\nTP% = (Titration Reading × Factor × 100) / CP',
  },
  {
    id: 'npn',
    name: 'Non-Protein Nitrogen (NPN)',
    category: 'Protein Quality',
    procedure: [
      'Take 1g sample in 100ml beaker, add 25ml 5% TCA solution.',
      'Stir on magnetic stirrer for 20 minutes.',
      'Cover and place in hot air oven at 60°C for 15 minutes.',
      'Filter with vacuum pump — put FILTRATE in digestion flask.',
      'Add 5g digestion mixture and 10ml lab-grade H₂SO₄.',
      'Heat at 500-600°C for 60-80 min until light green.',
      'Follow same procedure as CP estimation.',
    ],
    calculations: 'Factor = 8.75\nNPN% = (Titration Reading × Factor) / 6.25\nOr: NPN% = (CP − (TP Titration × 8.75)) / 6.25',
  },
  {
    id: 'aia',
    name: 'Acid Insoluble Ash (AIA)',
    category: 'Ash Analysis',
    apparatus: ['Crucible', 'Hot plate', 'Furnace', 'Beaker', 'Filter paper #44'],
    reagentPreparation: [
      { name: '10% HCl Solution', steps: ['Take 270ml HCl (37%)', 'Make 1000ml with distilled water'] },
    ],
    procedure: [
      'Take 5g sample and place in furnace for 3 hours.',
      'Take it out and put in a beaker.',
      'Add 20ml 10% HCl.',
      'Heat for 3-5 minutes on hot plate.',
      'Filter with #44 filter paper and add residue in weighed crucible (W1).',
      'Place in furnace for 2 hours, then weigh (W2).',
    ],
    calculations: 'AIA% = (W2 − W1) / Sample Weight × 100',
  },
  {
    id: 'ffa',
    name: 'Free Fatty Acid Analysis (FFA)',
    category: 'Oil & Fat Analysis',
    principle: 'Free fatty acid value reflects the number of fatty acids hydrolyzed from triacylglycerol. A liquid fat sample combined with neutralized 95% ethanol is titrated with NaOH to a phenolphthalein endpoint.',
    procedure: [
      'Take 50ml of spirit or ethanol.',
      'Add 3-4 drops of 1% phenolphthalein indicator.',
      'Add a few drops of 0.1N NaOH until purple-pinkish color appears.',
      'Add oil sample (3g for crude oil, 10g for refined oil) and heat for 2-3 min.',
      'Titrate with 0.1N NaOH and note the reading.',
    ],
    calculations: 'FFA% = (0.1 × 282 × Titration Reading × 100) / (Sample Weight × 1000)',
  },
  {
    id: 'pov',
    name: 'Peroxide Value Analysis (POV)',
    category: 'Oil & Fat Analysis',
    principle: 'The peroxide value is the equivalents of peroxides per kilogram of fat. Excess potassium iodide reacts with peroxides; liberated iodine is titrated with sodium thiosulfate using starch indicator.',
    reagentPreparation: [
      { name: '0.01N Sodium Thiosulfate', steps: ['Take 2.48g sodium thiosulfate', 'Make 1000ml with DW (or 0.62g in 250ml)'] },
    ],
    procedure: [
      'Take 5g sample in a conical flask.',
      'Add 18ml acetic acid (glacial) and 12ml chloroform (lab grade).',
      'Make saturated KI solution (1-1.5ml), add 0.5ml to sample.',
      'Slightly heat and shake. Place in darkness for 5 minutes.',
      'Add 30ml distilled water.',
      'Add 1-1.5ml 2% starch indicator until black color appears.',
      'Titrate with 0.01N sodium thiosulfate until 2 layers form.',
    ],
    calculations: 'POV (meq/kg) = (Titration Reading × 0.01 × 1000) / Sample Weight',
  },
  {
    id: 'toxin',
    name: 'Toxin Estimation (Aflatoxin)',
    category: 'Contaminant Analysis',
    procedure: [
      'Take 20g ground sample and add 100ml methanol solution (70%).',
      'Blend for 5 minutes.',
      'Filter with Whatman #1 paper in 100ml conical flask.',
      'NOTE: 1ml filter sample + 3ml methanol (70%) in 100ml beaker.',
      'Add 100μl conjugate solution in every sample and standard wells.',
      'Put Std. Solution in red wells (1-2-3-4): 0, 5, 15, 50 at 100μl. Add test samples 100μl to other wells.',
      'Mix very well.',
      'Add 100μl to antibody wells. Mix and wait 2 minutes.',
      'Wash antibody wells 5 times with distilled water. Dry carefully.',
      'Add 100μl substrate solution. Cover for 3 minutes.',
      'Add 100μl stop reagent. Mix well.',
      'Run test on Neogen micro reader (Model 4700), select aflatoxin.',
    ],
  },
  {
    id: 'lysine',
    name: 'Lysine Determination',
    category: 'Amino Acid Analysis',
    apparatus: ['Conical flask', 'Spectrophotometer', 'Centrifuge Machine'],
    reagentPreparation: [
      { name: 'Lysine Buffer Solution', steps: ['Take 27.99g oxalic acid, 3.4g KH₂PO₄, and 60ml glacial acetic acid', 'Make 1000ml with DW'] },
      { name: 'Orange B Solution', steps: ['Take 0.6815g orange B indicator', 'Make 500ml with lysine buffer solution'] },
      { name: 'Sodium Acetate Solution', steps: ['Take 16.4g sodium acetate', 'Make 100ml with DW'] },
    ],
    procedure: [
      'Grind sample and sieve with #60 sieve.',
      'Take 2 samples in X and Y labeled flasks (sample weight varies by material).',
      'Sample X: Add sample + 2ml sodium acetate → shake 15 min → add 40ml orange B → shake 3 hours → centrifuge 15 min → take 1ml supernatant in 100ml flask, fill with lysine buffer.',
      'Sample Y: Same as X but add 0.2ml propionic acid before shaking.',
      'Blank: 40ml orange B + 2ml sodium acetate → take 1ml in 100ml flask, fill with lysine buffer.',
      'Set spectrophotometer at 486nm. Check lysine buffer reading and subtract.',
      'Note readings of X, Y, and blank.',
    ],
    calculations: 'Available Lysine% = (Blank × (Y − X) × 22.747 × 100) / (Sample Weight × 1000)',
  },
  {
    id: 'rise-in-ph',
    name: 'Rise in pH (Urease Activity)',
    category: 'Quality Control',
    principle: 'Urease breaks down urea into ammonia and CO₂. Ammonia increases pH. Greater pH rise indicates higher urease activity suggesting inadequate heat treatment.',
    reagentPreparation: [
      { name: 'Phosphate Buffer Solution', steps: ['Take 0.8507g KH₂PO₄ (99%) and 1.088g K₂HPO₄', 'Make 250ml with DW', 'Adjust pH to 7'] },
      { name: 'Urea Buffer Solution', steps: ['Take 3g urea (99.5%)', 'Make 100ml with phosphate buffer solution', 'Adjust pH to 7', 'Add 1ml toluene'] },
    ],
    procedure: [
      'Sieve material with #60 sieve.',
      'Take 2 samples in two beakers (0.2g each).',
      'Add 10ml urea buffer in beaker #1, 10ml phosphate buffer in beaker #2.',
      'Cover with aluminum foil.',
      'Place in oven for 30 min at 35°C.',
      'Check pH through pH meter.',
    ],
    calculations: 'Rise in pH = U − P\n(U = urea beaker, P = phosphate beaker)',
    resultInterpretation: '0.05-0.2 = Properly toasted\n< 0.05 = Over toasted\n> 0.2 = Under-toasted (Not safe)',
  },
  {
    id: 'cv-mixer',
    name: 'CV of Mixer (Coefficient of Variation)',
    category: 'Quality Control',
    principle: 'The coefficient of variation measures how uniformly components are distributed throughout a mixture.',
    apparatus: ['Spectrophotometer', 'Beakers'],
    reagents: ['Ethanol', 'Methyl Violet'],
    procedure: [
      'Take 1000ml beaker, fill with ground maize (sieve with #20 sieve).',
      'Add methyl violet (11g/Ton) in center. Grind and sieve methyl violet with #120 sieve first.',
      'Add material into mixer by dumping.',
      'After mixing, take 10 samples from different places in mixer.',
      'Take 10g from each sample in 10 different 100ml beakers.',
      'Add 30ml ethanol to each flask and shake with stirrer.',
      'Shake 2 more times at 10-minute intervals.',
      'Filter each with #595 or #44 Whatman filter paper.',
      'Set spectrophotometer at 590nm.',
      'Note ethanol reading first and subtract. Note each sample reading.',
    ],
    calculations: 'Mean = Sum of observations / Total observations\nStd Dev = √(Σ(Xi − μ)² / (N−1))\nCV% = (Std Dev / Mean) × 100',
    resultInterpretation: 'CV of mixer should be between 5-10%.',
  },
  {
    id: 'glucosinolate',
    name: 'Glucosinolate Estimation',
    category: 'Contaminant Analysis',
    apparatus: ['Water Bath', 'Furnace', 'Hot plate'],
    reagentPreparation: [
      { name: '5% Barium Chloride Solution', steps: ['Take 50g barium chloride (99%)', 'Make 1000ml with DW'] },
    ],
    procedure: [
      'Take 10g sample in 1000ml beaker, add 500ml DW.',
      'Place in water bath for 1 hour at 54°C.',
      'Boil on hot plate for 2 hours.',
      'Filter and put filtrate in water bath at 100°C for 30 min.',
      'When filtrate temp equals water bath, add 20ml 5% BaCl₂.',
      'Wait 20-30 min, add 20ml BaCl₂ again.',
      'Wait 20-30 min, add 20ml BaCl₂ again.',
      'Wait 30 min — precipitates appear.',
      'Filter with ashless filter paper #44.',
      'Put residue in furnace (600°C) for 2 hours in weighed crucible (W1).',
      'Cool and weigh (W2).',
    ],
    calculations: 'Glucosinolate (μmol/g) = (W2 − W1) × 428.4637 / Sample Weight',
  },
  {
    id: 'chromium',
    name: 'Chromium Estimation',
    category: 'Contaminant Analysis',
    reagentPreparation: [
      { name: '1% Diphenyl Carbazide Solution', steps: ['1g DC indicator (97%+) in 50ml methanol, mix well', 'Add 50ml DW', 'Keep in color flask or cover with foil'] },
      { name: '20% H₂SO₄ Solution', steps: ['Take 21ml lab grade H₂SO₄', 'Make 100ml with DW', 'Keep covered'] },
    ],
    procedure: [
      'Take 5g sample in crucible, place in furnace for 2 hours.',
      'Pour ash into petri dish and wet drop by drop with 20% H₂SO₄.',
      'Add diphenyl carbazide indicator drop by drop.',
      'Wait 20-30 seconds and observe color.',
    ],
    resultInterpretation: 'Red color = Positive\nNo change = Negative',
  },
  {
    id: 'soap-test',
    name: 'Soap Test (Oil)',
    category: 'Oil & Fat Analysis',
    procedure: [
      'Take 10ml water in 100ml beaker.',
      'Add 8-10 drops of phenolphthalein indicator.',
      'Heat for 1 minute in oven.',
      'Transfer water to test tube.',
      'Add 10ml oil sample to test tube.',
      'Shake and observe after 2-3 minutes.',
    ],
    resultInterpretation: 'Positive = Fully Pinkish color\nNegative = No color (Transparent)\nSlightly Positive = Slightly Pinkish',
  },
  {
    id: 'urease-activity',
    name: 'Urease Activity (Spot Test)',
    category: 'Quality Control',
    principle: 'Urease catalyzes hydrolysis of urea into ammonia and CO₂. Ammonia raises pH. Phenol red indicator changes from yellow (acidic) to red/pink (alkaline).',
    reagentPreparation: [
      { name: 'Urea Solution', steps: ['Take 1000ml beaker, add 900ml DW', 'Add 63g urea (46%), mix well', 'Add 21ml 0.1N NaOH and 0.42g phenol red indicator', 'Mix well', 'Add 0.1N H₂SO₄ drop by drop until orange color'] },
    ],
    procedure: [
      'Take 10-15g soybean meal sample in a petri dish.',
      'Add urea solution over it.',
      'Wait 5 minutes and observe spots.',
    ],
    resultInterpretation: 'Nil spots = Properly toasted (if rise in pH > 0.05)\n1-15 spots = Acceptable\n> 20 spots = Under-toasted (Not safe)',
  },
  {
    id: 'calcium-wet',
    name: 'Calcium Estimation - Wet Digestion (Grains & Feed)',
    category: 'Mineral Analysis',
    reagents: ['Nitric acid 65%', 'Perchloric Acid 70%', '4N NaOH', 'Calcium Mixture', '0.01N EDTA'],
    reagentPreparation: [
      { name: '0.01N EDTA Solution', steps: ['Take 0.186g EDTA (99%)', 'Make 100ml with DW'] },
      { name: 'Calcium Mixture', steps: ['Take 100g Potassium Sulfate', 'Add 1g milute indicator', 'Grind and mix well'] },
    ],
    procedure: [
      'Take 0.5g sample in conical flask.',
      'Add 10ml nitric acid (65%), place on burner (500-600°C).',
      'After 5 min (digestion complete), add 5ml perchloric acid 70%, heat 5-8 min more.',
      'Cool, make volume 100ml with DW in volumetric flask.',
      'In china dish: add 20ml DW + 8-10 drops 4N NaOH + 0.001g calcium mixture → purple-pink color.',
      'Add 1ml sample from volumetric flask → light pink appears.',
      'Titrate with 0.01N EDTA until purple-pink color returns. Note reading.',
    ],
    calculations: 'Factor = (0.01 × 20 × 100 × 100) / (0.5 × 1 × 1000) = 4\nCalcium% = Titration Reading × 4',
  },
  {
    id: 'calcium-acid',
    name: 'Calcium Estimation - Acid Digestion (DCP, MCP & Limestone)',
    category: 'Mineral Analysis',
    reagents: ['Nitric acid 65%', 'HCl 37%', '4N NaOH', 'Calcium Mixture', 'Digestion Solution', '0.01N EDTA'],
    reagentPreparation: [
      { name: 'Digestion Solution', steps: ['Take 300ml HCl (37%) + 100ml Nitric acid (65%) in ratio 3:1', 'Mix well, do not cover. Use after 24 hours'] },
    ],
    procedure: [
      'Take 0.5g sample in conical flask.',
      'Add 40ml digestion solution and mix (DO NOT heat).',
      'Make volume 100ml with DW.',
      'Take 5ml from this, make 100ml with DW in another flask.',
      'In china dish: add 20ml DW + 8-10 drops 4N NaOH + 0.001g calcium mixture → purple-pink.',
      'Add 1ml sample → light pink appears.',
      'Titrate with 0.01N EDTA until purple-pink. Note reading.',
    ],
    calculations: 'Factor = (0.01 × 20 × 100 × 20 × 100) / (0.5 × 1 × 1000) = 80\nCalcium% = Titration Reading × 80',
  },
  {
    id: 'phosphorus-feed',
    name: 'Phosphorus Estimation (Feed & Grains)',
    category: 'Mineral Analysis',
    reagents: ['KH₂PO₄ Standards', 'Ammonium molybdate', 'Ammonium Metavanadate', 'HCl', 'Nitric acid 65%', 'Perchloric Acid 70%'],
    reagentPreparation: [
      { name: 'AMV Solution', steps: ['Take 2.5g ammonium molybdate, 0.125g ammonium metavanadate, 33ml HCl', 'Make 100ml with DW'] },
    ],
    procedure: [
      'Take 0.5g sample in conical flask.',
      'Add 10ml nitric acid, place on hot plate (300°C).',
      'After 5 min, add 5ml perchloric acid, heat again.',
      'Cool, make volume 100ml with DW.',
      'Prepare 7 test tubes: 5 standards (0.005-0.025) + 1 sample + 1 blank.',
      'Each tube: 1ml solution + 2ml AMV solution + 7ml DW.',
      'Wait 10 min. Shake with vortex.',
      'Set spectrophotometer at 470nm. Note blank first, then all readings.',
    ],
    calculations: 'Phosphorus% = (Sample Absorbance × Slope + Intercept × 100) / Sample Weight',
  },
  {
    id: 'phosphorus-mineral',
    name: 'Phosphorus Estimation (DCP, MCP, MDCP & Limestone)',
    category: 'Mineral Analysis',
    procedure: [
      'Same digestion as Feed & Grains method.',
      'Prepare standards at higher concentrations: 0.25, 0.35, 0.45, 0.55, 0.65.',
      'Use 5% KH₂PO₄ solution (5g in 100ml DW) for standards.',
      'Prepare 7 test tubes with same AMV + DW proportions.',
      'Set spectrophotometer at 470nm. Read all.',
    ],
    calculations: 'Phosphorus% = (Sample Absorbance × Slope + Intercept × 100) / Sample Weight',
  },
  {
    id: 'pepsin-digestibility',
    name: 'Pepsin Digestibility Test',
    category: 'Protein Quality',
    apparatus: ['Conical flask', 'Water bath'],
    reagents: ['0.075N HCl', 'Pepsin powder', '0.1N HCl', 'H₂SO₄', 'Digestion mixture'],
    reagentPreparation: [
      { name: '0.075N HCl Solution', steps: ['Take 6.2ml 37% HCl', 'Make 1000ml with DW'] },
      { name: '0.1N HCl Solution', steps: ['Take 64.1ml 37% HCl', 'Make 500ml with DW'] },
    ],
    procedure: [
      'Take 2g ground feed + 0.333g pepsin powder (≥3200 units/mg) + 450ml 0.075N HCl in conical flask.',
      'Cover, put in water bath for 48 hours at 41°C.',
      'Cool down. Add 10ml 0.1N HCl + 40ml DW to make 500ml.',
      'Take 250ml filtrate, add 30ml H₂SO₄ + 5g digestion mixture.',
      'Heat for 3.5 hours.',
      'Make dilution to 250ml, then distill as in protein estimation.',
      'Titrate against 0.1N H₂SO₄.',
    ],
    calculations: 'Pepsin Digestibility% = (Titration Reading × 21.875 × 100) / CP%',
  },
];
